services:
  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - app_network

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "100.110.104.100:3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  suit_sonia:
    image: druga98/suit:latest
    restart: always
    env_file:
      - .s.env
    depends_on:
      - db
    networks:
      - app_network

  mutual_be:
    image: druga98/mutual_be:latest
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .m.env
    depends_on:
      - db
    networks:
      - app_network

  el_estribo_be:
    image: druga98/el_estribo_be:latest
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .e.env
    depends_on:
      - db
    networks:
      - app_network

  casa_sonia_compras:
    image: druga98/casa_sonia_compras:latest
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .csc.env
    depends_on:
      - db
    networks:
      - app_network
    volumes:
      - casa_sonia_uploads:/app/public/uploads

  caran6:
    image: druga98/caran6:latest
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .caran.env
    depends_on:
      - db
    networks:
      - app_network

  estudio_r:
    image: druga98/estudio_r:latest
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .er.env
    depends_on:
      - db
    networks:
      - app_network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "100.110.104.100:9000:9000" # <- acá va tu IP de Tailscale
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  bot:
    image: druga98/bot_via_nova:latest
    networks:
      - app_network
    env_file:
      - .bot.env
    restart: unless-stopped
volumes:
  db_data:
    external: true
  npm_data:
  npm_letsencrypt:
  casa_sonia_uploads:
  portainer_data:

networks:
  app_network:
    driver: bridge
